### ISSUE TITLE
MacOS Install

### ISSUE THREAD

**Issue by rleikis** [barcradio/ultra-tracker#27]

**Comment by JordenLuke** [comment]
I was able to get it build the installer on the mac. When  Iran the installer app seamed to be running but there wasn't any progress nor did the seam be installed after the window sat open.

**Comment by cartpauj** [comment]
I installed on my MacBook Air (M2) running latest Sonoma. It wouldn't let me run it due to unverified developer.

If i right click the app icon, I can select Run and it allowed me to run it that way. But no windows are present.

https://cdn.zappy.app/fc8cdbd98df5c2b9f1fccdb0296e71cd.png

**Comment by JordenLuke** [comment]
Paste from Issue #120 

running the coomap froom the Applications Rolder:
barc@BARCs-MacBook-Pro /Applications % open ./ultra-tracker.app/Contents/MacOS/ultra-tracker

Last login: Wed Sep 18 23:02:44 on ttys000
barc@BARCs-MacBook-Pro ~ % /Applications/ultra-tracker.app/Contents/MacOS/ultra-tracker ; exit;
23:03:43.327 (startup) › Application execution path:/Applications/ultra-tracker.app/Contents/Resources/app.asar
Not in development mode, skipping DevTools installation.
[2024-09-19T05:03:43.377Z] [info] [main] -------------------------------------
| |
| Ultra-tracker |
| |
-------------------------------------
[2024-09-19T05:03:43.411Z] [info] [main] Initializing application: Log from the main process
[2024-09-19T05:03:43.419Z] [info] [main] Unable to connect or create database: dlopen(/var/folders/pr/q7rj50656ss1dj6m_qpqkn_w0000gn/T/.com.electron.app.6RQv3n, 0x0001): tried: '/var/folders/pr/q7rj50656ss1dj6m_qpqkn_w0000gn/T/.com.electron.app.6RQv3n' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h))), '/private/var/folders/pr/q7rj50656ss1dj6m_qpqkn_w0000gn/T/.com.electron.app.6RQv3n' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))
Unable to connect or create database: dlopen(/var/folders/pr/q7rj50656ss1dj6m_qpqkn_w0000gn/T/.com.electron.app.6RQv3n, 0x0001): tried: '/var/folders/pr/q7rj50656ss1dj6m_qpqkn_w0000gn/T/.com.electron.app.6RQv3n' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h))), '/private/var/folders/pr/q7rj50656ss1dj6m_qpqkn_w0000gn/T/.com.electron.app.6RQv3n' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64h)))
[2024-09-19T05:03:43.420Z] [info] [main] validateDatabaseTables
validateDatabaseTables
[2024-09-19T05:03:43.421Z] [error] [main] Unhandled rejection Error: Database connection not initialized
at getDatabaseConnection (/Applications/ultra-tracker.app/Contents/Resources/app.asar/out/main/index.js:34:18)
at getTableNames (/Applications/ultra-tracker.app/Contents/Resources/app.asar/out/main/index.js:119:15)
at validateDatabaseTables (/Applications/ultra-tracker.app/Contents/Resources/app.asar/out/main/index.js:109:22)
at App. (/Applications/ultra-tracker.app/Contents/Resources/app.asar/out/main/index.js:16386:3)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[20483:0918/230345.459095:ERROR:service_worker_storage.cc(2016)] Failed to delete the database: Database IO error

**Comment by cartpauj** [comment]
However, even though it opened on my M2, it's still not working properly. I get the same issue I reported about the Chromebook here - where the notes will not save: https://github.com/barcradio/ultra-tracker/issues/119

**Comment by JordenLuke** [comment]
PR 198 should fix this issue
